services:
  nginx:
    image: nginx:alpine
    container_name: orthanc-proxy
    ports:
      - "8000:80"
      - "4242:4242"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/ssl/certs
    depends_on:
      - orthanc
    restart: unless-stopped

  postgres:
    image: postgres:13
    command: ["postgres", "-c", "max_connections=200"]
    container_name: orthanc-postgres
    environment:
      POSTGRES_DB: orthanc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpassword
    ports:
      - "5433:5432"
    volumes:
      # - ./docker/postgres-data:/var/lib/postgresql/data
      - D:/docker/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    container_name: orthanc-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Web console
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345 # change in prod
    volumes:
      # - ./docker/minio-data:/data
      - D:/docker/minio-data:/data
    restart: unless-stopped

  orthanc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orthanc
    volumes:
      - ./src:/src
      - ./orthanc:/etc/orthanc
      - D:/docker/orthanc-data/:/var/lib/orthanc/db
    expose:
      - "8042"
      - "4242"
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      ORTHANC__Name: "save-images"
      ORTHANC__DicomAet: "SAVE_IMAGES"
      INSTANCE_BEHAVIOR_TEST: "None"
      INSTANCE_BEHAVIOR_SAVE: "true"
    restart: no
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-sfu", "demo:demo", "http://localhost:8042/system"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
